#!/bin/bash
cd $(dirname $0)

#Get plugin info from package.json
echo "Grabbing plugin info from $1"
CHARTNAME=$(cat $1 | jq ".name" | tr -d '"')
CHARTVERSION=$(cat $1 | jq ".version" | tr -d '"')
DIR=$(dirname "$1")

#Clone plugin-server repo
git clone https://github.com/rancher/ui-plugin-server.git
mv ui-plugin-server $CHARTNAME-chart

#Move files in from package.json filepath
rm -rf ./$CHARTNAME-chart/plugin/*
cp -r $DIR/pkg/* ./$CHARTNAME-chart/plugin

#Build Docker image with plugin files
cd $CHARTNAME-chart
docker buildx build --platform=linux/amd64 -f ./package/Dockerfile -t YOUR_DOCKERHUB_REPO_HERE/$CHARTNAME:v$CHARTVERSION --push .

#Edit Chart information to match plugin using yq and jq
yq -i ".name = \"${CHARTNAME}\"" ./charts/Chart.yaml
yq -i ".version = \"${CHARTVERSION}\"" ./charts/Chart.yaml
yq -i ".image.repository = \"eliyamlevy/${CHARTNAME}\"" ./charts/values.yaml
yq -i ".image.tag = \"v${CHARTVERSION}\"" ./charts/values.yaml
